import { ProductClass } from "@/models/Product";

export const productList = [
  {
    id: "AIExpension",
    imagePath: "/images/AIExpension.png",
    isIngredient: false,
    name: "AI Expension",
  },
  {
    id: "AILimiter",
    imagePath: "/images/AILimiter.png",
    isIngredient: false,
    name: "AI Limiter",
  },
  {
    id: "AlienDNACapsule",
    imagePath: "/images/AlienDNA.png",
    isIngredient: false,
    name: "Alien DNA Capsule",
  },
  {
    id: "AlienPowerMatrix",
    imagePath: "/images/AlienPowerMatrix.png",
    isIngredient: false,
    name: "Alien Power Matrix",
  },
  {
    id: "AlienProtein",
    imagePath: "/images/AlienProtein.png",
    isIngredient: false,
    name: "Alien Protein",
  },
  {
    id: "AluminumCasing",
    imagePath: "/images/AluminiumCasing.png",
    isIngredient: false,
    name: "Aluminum Casing",
  },
  {
    id: "AluminumIngot",
    imagePath: "/images/AluminiumIngot.png",
    isIngredient: false,
    name: "Aluminum Ingot",
  },
  {
    id: "AluminumScrap",
    imagePath: "/images/AluminiumScrap.png",
    isIngredient: false,
    name: "Aluminum Scrap",
  },
  {
    id: "AluminumPlate",
    imagePath: "/images/AluminiumSheet.png",
    isIngredient: false,
    name: "Aluminum Plate",
  },
  {
    id: "AssemblyDirectorSystem",
    imagePath: "/images/AssemblyDirectorSystem.png",
    isIngredient: false,
    name: "Assembly Director System",
  },
  {
    id: "BallisticWarpDrive",
    imagePath: "/images/BallisticWarpDrive.png",
    isIngredient: false,
    name: "Ballistic Warp Drive",
  },
  {
    id: "Battery",
    imagePath: "/images/Battery.png",
    isIngredient: false,
    name: "Battery",
  },
  {
    id: "Bauxite",
    imagePath: "/images/Bauxite.png",
    isIngredient: true,
    name: "Bauxite",
  },
  {
    id: "Beacon",
    imagePath: "/images/Beacon.png",
    isIngredient: false,
    name: "Beacon",
  },
  {
    id: "BiochemicalSculptor",
    imagePath: "/images/BiochemicalSculptor.png",
    isIngredient: false,
    name: "Biochemical Sculptor",
  },
  {
    id: "Biomass",
    imagePath: "/images/Biomass.png",
    isIngredient: false,
    name: "Biomass",
  },
  {
    id: "Cable",
    imagePath: "/images/Cables.png",
    isIngredient: false,
    name: "Cable",
  },
  {
    id: "CateriumIngot",
    imagePath: "/images/CateriumIngot.png",
    isIngredient: false,
    name: "Caterium Ingot",
  },
  {
    id: "CateriumOre",
    imagePath: "/images/CateriumOre.png",
    isIngredient: true,
    name: "Caterium Ore",
  },
  {
    id: "CircuitBoard",
    imagePath: "/images/CircuitBoard.png",
    isIngredient: false,
    name: "Circuit Board",
  },
  {
    id: "Cluster",
    imagePath: "/images/Cluster.png",
    isIngredient: false,
    name: "Cluster",
  },
  {
    id: "Coal",
    imagePath: "/images/CoalOre.png",
    isIngredient: true,
    name: "Coal",
  },
  {
    id: "ColorCartridge",
    imagePath: "/images/ColorCartridge.png",
    isIngredient: false,
    name: "Color Cartridge",
  },
  {
    id: "CompactedCoal",
    imagePath: "/images/CompactedCoal.png",
    isIngredient: false,
    name: "Compacted Coal",
  },
  {
    id: "Computer",
    imagePath: "/images/Computer.png",
    isIngredient: false,
    name: "Computer",
  },
  {
    id: "Concrete",
    imagePath: "/images/Concrete.png",
    isIngredient: false,
    name: "Concrete",
  },
  {
    id: "ConversionCube",
    imagePath: "/images/ConversionCube.png",
    isIngredient: false,
    name: "Conversion Cube",
  },
  {
    id: "CoolingSystem",
    imagePath: "/images/CoolingSystem.png",
    isIngredient: false,
    name: "Cooling System",
  },
  {
    id: "Copper",
    imagePath: "/images/copper.png",
    isIngredient: true,
    name: "Copper Ore",
  },
  {
    id: "CopperPowder",
    imagePath: "/images/CopperDust.png",
    isIngredient: false,
    name: "Copper Powder",
  },
  {
    id: "CopperIngot",
    imagePath: "/images/CopperIngot.png",
    isIngredient: false,
    name: "Copper Ingot",
  },
  {
    id: "CopperSheet",
    imagePath: "/images/CopperSheet.png",
    isIngredient: false,
    name: "Copper Sheet",
  },
  {
    id: "CrystalOscillator",
    imagePath: "/images/CrystalOscillator.png",
    isIngredient: false,
    name: "Crystal Oscillator",
  },
  {
    id: "DarkEnergy",
    imagePath: "/images/DarkEnergy.png",
    isIngredient: false,
    name: "Dark Energy",
  },
  {
    id: "Diamonds",
    imagePath: "/images/Diamonds.png",
    isIngredient: false,
    name: "Diamonds",
  },
  {
    id: "DissolvedSilica",
    imagePath: "/images/DissolvedSilica.png",
    isIngredient: false,
    name: "Dissolved Silica",
  },
  {
    id: "ElectromagneticControlRod",
    imagePath: "/images/ElectromagneticControlRod.png",
    isIngredient: false,
    name: "Electromagnetic Control Rod",
  },
  {
    id: "EmptyCanister",
    imagePath: "/images/EmptyCannister.png",
    isIngredient: false,
    name: "Empty Canister",
  },
  {
    id: "EncasedPlutoniumCell",
    imagePath: "/images/EncasedPlutoniumCell.png",
    isIngredient: false,
    name: "Encased Plutonium Cell",
  },
  {
    id: "EncasedSteelBeam",
    imagePath: "/images/EncasedSteelBeam.png",
    isIngredient: false,
    name: "Encased Steel Beam",
  },
  {
    id: "Motor",
    imagePath: "/images/Engine.png",
    isIngredient: false,
    name: "Motor",
  },
  {
    id: "ExoticMatter",
    imagePath: "/images/ExoticMatter.png",
    isIngredient: false,
    name: "Exotic Matter",
  },
  {
    id: "Explosive",
    imagePath: "/images/Explosive.png",
    isIngredient: false,
    name: "Explosive",
  },
  {
    id: "ExpRebar",
    imagePath: "/images/ExpRebar.png",
    isIngredient: false,
    name: "Exp Rebar",
  },
  {
    id: "Fabric",
    imagePath: "/images/Fabric.png",
    isIngredient: false,
    name: "Fabric",
  },
  {
    id: "FicsiteIngot",
    imagePath: "/images/FicsiteIngot.png",
    isIngredient: false,
    name: "Ficsite Ingot",
  },
  {
    id: "FicsiteMesh",
    imagePath: "/images/FicsiteMesh.png",
    isIngredient: false,
    name: "Ficsite Mesh",
  },
  {
    id: "Ficsit_Coupon",
    imagePath: "/images/Ficsit_Coupon.png",
    isIngredient: true,
    name: "Ficsit Coupon",
  },
  {
    id: "FicsoniumCell",
    imagePath: "/images/FicsoniumCell.png",
    isIngredient: false,
    name: "Ficsonium Cell",
  },
  {
    id: "FicsoniumFuelRod",
    imagePath: "/images/FicsoniumFuelRod.png",
    isIngredient: false,
    name: "Ficsonium Fuel Rod",
  },
  {
    id: "FlowerPetals",
    imagePath: "/images/FlowerPetals.png",
    isIngredient: false,
    name: "Flower Petals",
  },
  {
    id: "PackagedFuel",
    imagePath: "/images/Fuel.png",
    isIngredient: false,
    name: "Packaged Fuel",
  },
  {
    id: "FusedModularFrame",
    imagePath: "/images/FusedModularFrame.png",
    isIngredient: false,
    name: "Fused Modular Frame",
  },
  {
    id: "Gas",
    imagePath: "/images/Gas.png",
    isIngredient: false,
    name: "Gas",
  },
  {
    id: "GasMaskFilter",
    imagePath: "/images/GasMaskFilter.png",
    isIngredient: false,
    name: "Gas Mask Filter",
  },
  {
    id: "Gunpowder",
    imagePath: "/images/Gunpowder.png",
    isIngredient: false,
    name: "Gunpowder",
  },
  {
    id: "GunpowderMk2",
    imagePath: "/images/GunpowderMk2.png",
    isIngredient: false,
    name: "Gunpowder Mk2",
  },
  {
    id: "HazmatFilter",
    imagePath: "/images/HazmatFilter.png",
    isIngredient: false,
    name: "Hazmat Filter",
  },
  {
    id: "HeatSink",
    imagePath: "/images/Heatsink.png",
    isIngredient: false,
    name: "HeatSink",
  },
  {
    id: "HighSpeedConnector",
    imagePath: "/images/HighSpeedConnector.png",
    isIngredient: false,
    name: "High Speed Connector",
  },
  {
    id: "HomingRifle",
    imagePath: "/images/HomingRifle.png",
    isIngredient: false,
    name: "Homing Rifle",
  },
  {
    id: "IonizedFuel",
    imagePath: "/images/IonizedFuel.png",
    isIngredient: false,
    name: "Ionized Fuel",
  },
  {
    id: "IonizedRocketFuel",
    imagePath: "/images/IonizedRocketFuel.png",
    isIngredient: false,
    name: "Ionized Rocket Fuel",
  },
  {
    id: "Iron",
    imagePath: "/images/iron.png",
    isIngredient: true,
    name: "Iron Ore",
  },
  {
    id: "IronIngot",
    imagePath: "/images/IronIngot.png",
    isIngredient: false,
    name: "Iron Ingot",
  },
  {
    id: "IronPlate",
    imagePath: "/images/IronPlates.png",
    isIngredient: false,
    name: "Iron Plate",
  },
  {
    id: "IronRod",
    imagePath: "/images/IronRods.png",
    isIngredient: false,
    name: "Iron Rod",
  },
  {
    id: "IronScrew",
    imagePath: "/images/IronScrews.png",
    isIngredient: false,
    name: "Iron Screw",
  },
  {
    id: "Leaves",
    imagePath: "/images/Leaves.png",
    isIngredient: true,
    name: "Leaves",
  },
  {
    id: "Alumina",
    imagePath: "/images/LiquidAlumina_Pipe.png",
    isIngredient: false,
    name: "Alumina",
  },
  {
    id: "PackagedBiofuel",
    imagePath: "/images/LiquidBiofuel.png",
    isIngredient: false,
    name: "Packaged Biofuel",
  },
  {
    id: "Biofuel",
    imagePath: "/images/LiquidBiofuel_Pipe.png",
    isIngredient: false,
    name: "Biofuel",
  },
  {
    id: "Fuel",
    imagePath: "/images/LiquidFuel_Pipe.png",
    isIngredient: false,
    name: "Fuel",
  },
  {
    id: "HeavyOilResidue",
    imagePath: "/images/LiquidHeavyOilResidue_Pipe.png",
    isIngredient: false,
    name: "Heavy Oil Residue",
  },
  {
    id: "Oil",
    imagePath: "/images/LiquidOil_Pipe.png",
    isIngredient: false,
    name: "Oil",
  },
  {
    id: "SulfuricAcid",
    imagePath: "/images/LiquidSulfuricAcid_Pipe.png",
    isIngredient: false,
    name: "Sulfuric Acid",
  },
  {
    id: "TurboFuel",
    imagePath: "/images/LiquidTurboFuel_Pipe.png",
    isIngredient: false,
    name: "Turbo Fuel",
  },
  {
    id: "Water",
    imagePath: "/images/LiquidWater_Pipe.png",
    isIngredient: true,
    name: "Water",
  },
  {
    id: "MagneticFieldGenerator",
    imagePath: "/images/MagneticFieldGenerator.png",
    isIngredient: false,
    name: "Magnetic Field Generator",
  },
  {
    id: "ModularFrame",
    imagePath: "/images/ModularFrame.png",
    isIngredient: false,
    name: "Modular Frame",
  },
  {
    id: "ModularFrameHeavy",
    imagePath: "/images/ModularFrameHeavy.png",
    isIngredient: false,
    name: "Modular Frame Heavy",
  },
  {
    id: "Mycelia",
    imagePath: "/images/Mycelia.png",
    isIngredient: true,
    name: "Mycelia",
  },
  {
    id: "NitricAcid",
    imagePath: "/images/NitricAcid.png",
    isIngredient: false,
    name: "Nitric Acid",
  },
  {
    id: "NitrogenGas",
    imagePath: "/images/NitrogenGas.png",
    isIngredient: false,
    name: "Nitrogen Gas",
  },
  {
    id: "NonFissileUranium",
    imagePath: "/images/NonFissileUranium.png",
    isIngredient: false,
    name: "Non Fissile Uranium",
  },
  {
    id: "UraniumCell",
    imagePath: "/images/NuclearCell.png",
    isIngredient: false,
    name: "Uranium Cell",
  },
  {
    id: "NuclearFuelRod",
    imagePath: "/images/NuclearFuelRod.png",
    isIngredient: false,
    name: "Nuclear Fuel Rod",
  },
  {
    id: "NuclearPasta",
    imagePath: "/images/NuclearPasta.png",
    isIngredient: false,
    name: "Nuclear Pasta",
  },
  {
    id: "NuclearWaste",
    imagePath: "/images/NuclearWaste.png",
    isIngredient: false,
    name: "Nuclear Waste",
  },
  {
    id: "Nuke",
    imagePath: "/images/Nuke.png",
    isIngredient: false,
    name: "Nuke",
  },
  {
    id: "PackagedOil",
    imagePath: "/images/Oil.png",
    isIngredient: true,
    name: "PackagedOil",
  },
  {
    id: "PackagedOilResidue",
    imagePath: "/images/OilResidue.png",
    isIngredient: false,
    name: "Packaged Oil Residue",
  },
  {
    id: "PackagedAluminaSolution",
    imagePath: "/images/PackagedAluminaSolution.png",
    isIngredient: false,
    name: "Packaged Alumina Solution",
  },
  {
    id: "PackagedNitricAcid",
    imagePath: "/images/PackagedNitricAcid.png",
    isIngredient: false,
    name: "Packaged Nitric Acid",
  },
  {
    id: "PackagedNitrogenGas",
    imagePath: "/images/PackagedNitrogen.png",
    isIngredient: false,
    name: "Packaged Nitrogen Gas",
  },
  {
    id: "PackagedRocketFuel",
    imagePath: "/images/PackagedRocketFuel.png",
    isIngredient: false,
    name: "Packaged Rocket Fuel",
  },
  {
    id: "PackagedWater",
    imagePath: "/images/PackagedWater.png",
    isIngredient: false,
    name: "Packaged Water",
  },
  {
    id: "PackagedSulfuricAcid",
    imagePath: "/images/PckagedSulphuricAcid.png",
    isIngredient: false,
    name: "Packaged Sulfuric Acid",
  },
  {
    id: "PetroleumCoke",
    imagePath: "/images/PetroleumCoke.png",
    isIngredient: false,
    name: "Petroleum Coke",
  },
  {
    id: "Plastic",
    imagePath: "/images/Plastic.png",
    isIngredient: false,
    name: "Plastic",
  },
  {
    id: "PlutoniumFuelRod",
    imagePath: "/images/PlutoniumFuelRod.png",
    isIngredient: false,
    name: "Plutonium Fuel Rod",
  },
  {
    id: "PlutoniumPellet",
    imagePath: "/images/PlutoniumPellet.png",
    isIngredient: false,
    name: "Plutonium Pellet",
  },
  {
    id: "PlutoniumWaste",
    imagePath: "/images/PlutoniumWaste.png",
    isIngredient: false,
    name: "Plutonium Waste",
  },
  {
    id: "PolymerResin",
    imagePath: "/images/PolymerResin.png",
    isIngredient: false,
    name: "Polymer Resin",
  },
  {
    id: "PowerShard",
    imagePath: "/images/PowerShard.png",
    isIngredient: false,
    name: "Power Shard",
  },
  {
    id: "PowerSlugGreen",
    imagePath: "/images/PowerSlugGreen.png",
    isIngredient: false,
    name: "Power Slug Green",
  },
  {
    id: "PowerSlugPurple",
    imagePath: "/images/PowerSlugPurple.png",
    isIngredient: false,
    name: "Power Slug Purple",
  },
  {
    id: "PowerSlugYellow",
    imagePath: "/images/PowerSlugYellow.png",
    isIngredient: false,
    name: "Power Slug Yellow",
  },
  {
    id: "PressureTank",
    imagePath: "/images/PressureTank.png",
    isIngredient: false,
    name: "Pressure Tank",
  },
  {
    id: "QuantumComputer",
    imagePath: "/images/QuantumComputer.png",
    isIngredient: false,
    name: "Quantum Computer",
  },
  {
    id: "QuantumEnergy",
    imagePath: "/images/QuantumEnergy.png",
    isIngredient: false,
    name: "Quantum Energy",
  },
  {
    id: "RawQuartz",
    imagePath: "/images/QuartzCrystal.png",
    isIngredient: true,
    name: "Raw Quartz",
  },
  {
    id: "QuartzResource",
    imagePath: "/images/QuartzResource.png",
    isIngredient: false,
    name: "QuartzResource",
  },
  {
    id: "Quickwire",
    imagePath: "/images/Quickwire.png",
    isIngredient: false,
    name: "Quickwire",
  },
  {
    id: "RadioControlUnit",
    imagePath: "/images/RadioControlUnit.png",
    isIngredient: false,
    name: "Radio Control Unit",
  },
  {
    id: "ReanimatedSam",
    imagePath: "/images/ReanimatedSam.png",
    isIngredient: false,
    name: "Reanimated Sam",
  },
  {
    id: "Rebar",
    imagePath: "/images/Rebar.png",
    isIngredient: false,
    name: "Rebar",
  },
  {
    id: "IronPlateReinforced",
    imagePath: "/images/ReinforcedIronPlates.png",
    isIngredient: false,
    name: "Iron Plate Reinforced",
  },
  {
    id: "Rifle",
    imagePath: "/images/Rifle.png",
    isIngredient: false,
    name: "Rifle",
  },
  {
    id: "RocketFuelPipe",
    imagePath: "/images/RocketFuelPipe.png",
    isIngredient: false,
    name: "Rocket Fuel Pipe",
  },
  {
    id: "Rotor",
    imagePath: "/images/Rotor.png",
    isIngredient: false,
    name: "Rotor",
  },
  {
    id: "Rubber",
    imagePath: "/images/Rubber.png",
    isIngredient: false,
    name: "Rubber",
  },
  {
    id: "SamFluctuator",
    imagePath: "/images/SamFluctuator.png",
    isIngredient: false,
    name: "Sam Fluctuator",
  },
  {
    id: "SAM",
    imagePath: "/images/SAMOre.png",
    isIngredient: true,
    name: "SAM",
  },
  {
    id: "ScatterRebar",
    imagePath: "/images/ScatterRebar.png",
    isIngredient: false,
    name: "Scatter Rebar",
  },
  {
    id: "Shock",
    imagePath: "/images/Shock.png",
    isIngredient: false,
    name: "Shock",
  },
  {
    id: "Silica",
    imagePath: "/images/Silica.png",
    isIngredient: false,
    name: "Silica",
  },
  {
    id: "SingularityCell",
    imagePath: "/images/SingularityCell.png",
    isIngredient: false,
    name: "Singularity Cell",
  },
  {
    id: "SolidBiofuel",
    imagePath: "/images/SolidBiofuel.png",
    isIngredient: false,
    name: "Solid Biofuel",
  },
  {
    id: "SpaceElevatorPart_1",
    imagePath: "/images/SpelevatorPart_1.png",
    isIngredient: false,
    name: "Space Elevator Part1",
  },
  {
    id: "SpaceElevatorPart_2",
    imagePath: "/images/SpelevatorPart_2.png",
    isIngredient: false,
    name: "Space Elevator Part2",
  },
  {
    id: "SpaceElevatorPart_3",
    imagePath: "/images/SpelevatorPart_3.png",
    isIngredient: false,
    name: "Space Elevator Part3",
  },
  {
    id: "SpaceElevatorPart_4",
    imagePath: "/images/SpelevatorPart_4.png",
    isIngredient: false,
    name: "Space Elevator Part4",
  },
  {
    id: "SpaceElevatorPart_5",
    imagePath: "/images/SpelevatorPart_5.png",
    isIngredient: false,
    name: "Space Elevator Part5",
  },
  {
    id: "Stator",
    imagePath: "/images/Stator.png",
    isIngredient: false,
    name: "Stator",
  },
  {
    id: "SteelBeam",
    imagePath: "/images/SteelBeam.png",
    isIngredient: false,
    name: "Steel Beam",
  },
  {
    id: "SteelIngot",
    imagePath: "/images/SteelIngot.png",
    isIngredient: false,
    name: "Steel Ingot",
  },
  {
    id: "SteelPipe",
    imagePath: "/images/SteelPipe.png",
    isIngredient: false,
    name: "Steel Pipe",
  },
  {
    id: "Limestone",
    imagePath: "/images/Stone.png",
    isIngredient: true,
    name: "Limestone",
  },
  {
    id: "StunRebar",
    imagePath: "/images/StunRebar.png",
    isIngredient: false,
    name: "Stun Rebar",
  },
  {
    id: "Sulfur",
    imagePath: "/images/Sulfur.png",
    isIngredient: true,
    name: "Sulfur",
  },
  {
    id: "SuperComputer",
    imagePath: "/images/SuperComputer.png",
    isIngredient: false,
    name: "Super Computer",
  },
  {
    id: "SuperPositionOscillator",
    imagePath: "/images/SuperPositionOscillator.png",
    isIngredient: false,
    name: "Super Position Oscillator",
  },
  {
    id: "TemporalProcessor",
    imagePath: "/images/TemporalProcessor.png",
    isIngredient: false,
    name: "Temporal Processor",
  },
  {
    id: "ThermalPropulsionRocket",
    imagePath: "/images/ThermalPropulsionRocket.png",
    isIngredient: false,
    name: "Thermal Propulsion Rocket",
  },
  {
    id: "TimeCrystal",
    imagePath: "/images/TimeCrystal.png",
    isIngredient: false,
    name: "Time Crystal",
  },
  {
    id: "PackagedTurboFuel",
    imagePath: "/images/TurboFuel.png",
    isIngredient: false,
    name: "Packaged Turbo Fuel",
  },
  {
    id: "TurboMotor",
    imagePath: "/images/TurboMotor.png",
    isIngredient: false,
    name: "Turbo Motor",
  },
  {
    id: "TurboRifle",
    imagePath: "/images/TurboRifle.png",
    isIngredient: false,
    name: "Turbo Rifle",
  },
  {
    id: "Uranium",
    imagePath: "/images/UraniumOre.png",
    isIngredient: true,
    name: "Uranium",
  },
  {
    id: "Wire",
    imagePath: "/images/Wire.png",
    isIngredient: false,
    name: "Wire",
  },
  {
    id: "Wood",
    imagePath: "/images/Wood.png",
    isIngredient: true,
    name: "Wood",
  },
] as ProductClass[];
